Feature/home page
WildCodeSchool/uss-enterprise pull request #1
Opened 2019-10-23 07:34 UTC by alejolale

I made the home page, presentation  name of game, start button, planet image.

2019-10-23 07:49 UTC, superfrancisco2019 commented
review made, everything ok

2019-10-23 08:09 UTC, Aebrathia commented
Hi,

- Components folder should be lowercase
- Each component and their folder should be written in PascalCase
- CSS Stylesheets should be linked at the end of head element
- Use import instead of require and outside of component
- Be careful of spacing and indentation
- You don't need 3 elements to style your start button
- Make your text uppercase using styles
- Indent everything inside media
- style generic html elements in index.css not in components
- You don't need @media min width 320px

Thanks !

2019-10-23 08:09 UTC, Aebrathia commented on public/index.html
> +    <link href="https://fonts.googleapis.com/css?family=Orbitron&display=swap" rel="stylesheet">
Move this

2019-10-23 09:08 UTC, superfrancisco2019 approved these changes
all changes have been made after the first pull request

2019-10-24 15:22 UTC, Aebrathia commented
You should name your component folder and files with PascalCase : HomePage/HomePage.js

2019-10-24 15:49 UTC, superfrancisco2019 approved these changes
ok

2019-10-28 08:40 UTC, Aebrathia commented
Images should be placed in the folder of the component hey are in :
- `/src/components/HomePage/HomePage.js`
- `/src/components/HomePage/HomePage.css`
- `/src/components/HomePage/my-image.png`

Images should also have explicit kebab-case names.

In case the same image is used by multiple components you can create a folder like this :
- `/src/images/` or
- `/src/img/`

If you don't need an image anymore remove it from the project.

2019-10-28 08:40 UTC, Aebrathia requested changes
Images should be placed in the folder of the component hey are in :

    /src/components/HomePage/HomePage.js
    /src/components/HomePage/HomePage.css
    /src/components/HomePage/my-image.png

Images should also have explicit kebab-case names.

In case the same image is used by multiple components you can create a folder like this :

    /src/images/ or
    /src/img/

If you don't need an image anymore remove it from the project.

2019-10-29 10:16 UTC, superfrancisco2019 commented
ok

2019-10-30 14:26 UTC, Aebrathia commented
Congrats first PR of all projects to be merged!

2019-10-30 14:26 UTC, Aebrathia approved these changes

2019-10-30 14:33 UTC, merged